config/routes.rb
CTAChallengeApp::Application.routes.draw do

  root :to => 'site#index'
 
  get '/site', :controller => :site, :action => :index

  get '/users', :controller => :users, :action => :index, :as => :users
  get '/user/:id', :controller => :users, :action => :show, :as => :user
  get '/users/new', :controller => :users, :action => :new, :as => :new_user
  post '/users/', :controller => :users, :action => :create
  get '/user/:id/edit', :controller => :users, :action => :edit, :as => :edit_user
  put 'user/:id/update', :controller => :users, :action => :update
  delete 'user/:id', :controller => :users, :action => :destroy

  get '/challenges', :controller => :challenges, :action => :index, :as => :challenges
  get '/challenge/:id', :controller => :challenges, :action => :show, :as => :challenge
  get '/challenges/new', :controller => :challenges, :action => :new, :as => :new_challenge
  post '/challenges/', :controller => :challenges, :action => :create
  get '/challenges/:id/edit', :controller => :challenges, :action => :edit, :as => :edit_challenge
  put '/challenges/:id/update', :controller => :challenges, :action => :update
  delete '/challenge/:id', :controller => :challenges, :action => :destroy

  get '/articles', :controller => :articles, :action => :index, :as => :articles
  get '/article/:id', :controller => :articles, :action => :show, :as => :article
  get '/articles/new', :controller => :articles, :action => :new, :as => :new_article
  post '/articles', :controller => :articles, :action => :create
  get '/articles/:id/edit', :controller => :articles, :action => :edit, :as => :edit_article
  put '/articles/:id/update', :controller => :artciles, :action => :update
  delete '/article/:id', :controller => :articles, :action => :destroy

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :link
  validates_uniqueness_of :title, :link
  validates_presence_of :title, :link
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  attr_accessible :date, :duration, :user, :username

  has_many :user_challenges
  has_many :users, :through  => :user_challenges
  validates_presence_of :date, :duration

  def self.winner
    Challenge.find(:first, :order => "duration desc")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :email

  has_many :user_challenges
  has_many :challenges, :through => :user_challenges

  validates_presence_of :username
  validates_uniqueness_of :email

  #not using default find_or_create_by since it requires
  #both name and email to match.  Code below accomdates
  #situations where names change.
  def self.find_or_create(name, email)
    user = User.find_by_email(email)
    unless user
      user = User.create(:username => name, :email => email)
    end
    user
  end
end

app/models/user_challenge.rb
class UserChallenge < ActiveRecord::Base
  belongs_to :challenge
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @articles = Article.find_by_id(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article])
    if @article.save
      flash[:success] = "Article added"
      redirect_to articles_url
    else
      flash[:error] = "Please try again."
      render 'new'
    end
  end

  def edit
    @article = Article.find_by_id(params[:id])
  end

  def update
    @article = Article.find_by_id(params[:id])
    if article.update_attributes(params[:artcile])
      flash[:success] = "Updated"
      redirect_to article_url
    else
      flash[:error] = "Please try again"
      render 'edit'
    end
  end

  def destroy
    Article.find_by_id(params[:id]).destroy
    flash[:sucess] = "Article has been deleted."
    redirect_to articles_url
  end

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  def index
    @challenges = Challenge.all
  end

  def show
    @challenge = Challenge.find_by_id(params[:id])
  end

  def new
    @challenge = Challenge.new
  end

  def create
    @challenge = Challenge.new(params[:challenge])
    user_name = params[:user][:name]
    user_email = params[:user][:email]
    user = @challenge.users.find_or_create(user_name, user_email)
    @challenge.users << user
    if @challenge.save
      flash[:success] = "New CTA Challenge has been added."
      redirect_to challenges_url
    else
      flash[:error] = "Please try again."
      render 'new'
    end
  end

  def edit
    @challenge = Challenge.find_by_id(params[:id])
  end

  def update
    @challenge = Challenge.find_by_id(params[:id])
    if @challenge.update_attributes(params[:challenge])
      flash[:success] = "Challenge updated"
      redirect_to challenge_url
    else
      flash[:error] = "Try that one more time"
      render 'edit'
    end
  end

  def destroy
    Challenge.find_by_id(params[:id]).destroy
    flash[:successs] = "Challenge has been deleted"
    redirect_to challenges_url
  end


end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
  def index
    @winner  = Challenge.winner
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  def index
    @users = User.all
  end
  
  def show
    @user = User.find_by_id(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome!"
      redirect_to users_url
    else
      render 'new'
      flash[:error] = "Please try again."
    end
  end

  def edit 
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      redirect_to user_url
    else
      render 'edit'
      flash[:error] = "Please try again."
    end
  end

  def destroy 
   User.find_by_id(params[:id]).destroy
   flash[:success] = "User has been deleted"
   redirect_to users_url 
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :link, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :link, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Add Article", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                articles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%- model_class = @article.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<%- model_class = Article.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:link) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.title, article.link %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_article_path(article), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              article_path(article),
              :method => :delete,
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-mini btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to t('.new', :default => t("helpers.links.new")),
      new_article_path,
      :class => 'btn btn-primary' %>

app/views/articles/new.html.erb
<%- model_class = @article.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<%- model_class = @article.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:link) %>:</strong><br>
  <%= @article.link %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              articles_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_article_path(@article), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              article_path(@article),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/challenges/_form.html.erb
<%= form_for @challenge, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>

  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :date, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :duration, :class => 'control-label' %>
    <div class="controls">
      <%= f.time_select :duration, :class => 'time_select' %>
    </div>
  </div>
  <%= f.fields_for :user  do |ff| %>

    <div class="control-group">
      <%= label_tag 'user[name]', 'Name',:class => 'control-label' %>
      <div class="controls">
        <%= text_field_tag 'user[name]', '',  :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= label_tag  'user[email]', 'Email',  :class => 'control-label' %>
      <div class="controls">
        <%= text_field_tag 'user[email]', '',  :class => 'text_field' %>
      </div>
    </div>
  <% end %>

  <div class="form-actions">
    <%= f.submit "Log it!", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      challenges_path, :class => 'btn' %>
    </div>
  <% end %>

app/views/challenges/edit.html.erb
<%- model_class = @challenge.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/challenges/index.html.erb
<%- model_class = Challenge.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:time) %></th>
      <th><%= model_class.human_attribute_name(:rider) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @challenges.each do |challenge| %>
      <tr>
        <td><%= link_to challenge.date.strftime(" %m/%d/%Y"), challenge_path(challenge) %></td>
        <td><%= link_to challenge.duration.strftime("%I h, %M m, %S s"), challenge_path(challenge) %></td>
        <% first_user = challenge.users.first %>
        <td><%= link_to first_user.username, user_path(first_user) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_challenge_path(challenge), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      challenge_path(challenge),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_challenge_path,
            :class => 'btn btn-primary' %>
            

app/views/challenges/new.html.erb
<%- model_class = @challenge.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/challenges/show.html.erb
<%- model_class = @challenge.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:date) %>:</strong><br>
  <%= @challenge.date %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:duration) %>:</strong><br>
  <%= @challenge.duration %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              challenges_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_challenge_path(@challenge), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              challenge_path(@challenge),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en" >
  <head>
    <title> CTA Challenge Scoreboard </title>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href= 'site#index' > CTA Challenge Scoreboard </a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "The Scoreboard", challenges_url  %></li>
              <li><%= link_to "Articles", articles_url  %></li>
              <li><%= link_to "Previous Record Holders", users_url  %></li>
            </ul>
          </div>
        </div>
      </div>
        <%= yield %>
    </body>
  </html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/site/index.html.erb
<center>
  
<p> 8 Train Lines </p>
<p> 144 Stations </p>
<p> No Bathrooms <p>
<br />
<h1> The CTA Challenge </h1>
<p> To complete the CTA Challenge you must ride all eight lines and hit every stop. <p>

<br />
<br />
<p> The Current Record for the CTA Challenge is </p>
<%= @winner.duration.strftime("%I Hours %M Minutes and %S seconds")  %>
<p> held by </p>
<%= @winner.users.first.username %>
<p>

<%= link_to  "Post your time", new_challenge_url %>
</p> 

</center>
         

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="control-group">
    <%= f.label :username, :class => 'control-label' %>
    <div class="countrols">
      <%= f.text_field :username, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = @user.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:username) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:admin) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = @user.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = @user.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:username) %>:</strong><br>
  <%= @user.username %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:email) %>:</strong><br>
  <%= @user.email %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:admin) %>:</strong><br>
  <%= @user.admin %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>